### PR TITLE
https://trello.com/c/NIcWUWRG - Bubble left anchor cyan

### PR DESCRIPTION
**Pull request by harshvchawla**
Why Tech text and image component with SVG scaling
- Code change authors: @harshvchawla & @dghazi12

### CODE REVIEW

**Comment by harshvchawla** [comment]
The merge conflicts are trivial and can be resolved by:
1) src/styles/global.css - accept the changes in `master` branch
2) src/pages/index.js- can accept changes in `master` branch & include the component inclusion line from the "bubble.." branch

**Comment by gh0stl0nely** [comment]
@harshvchawla It seems like the current branch we are merging is quite behind in terms of commits. Maybe you guys want to merge the changes from master to this branch first and create another pull request to keep it up to date and consistent?

**Comment by harshvchawla** [comment]
@gh0stl0nely have reorganized this PR's component acc to new folder structure. Can you pls review again?

**Review by gh0stl0nely — APPROVED** [review]
@harshvchawla  I think this is good.

**Comment by harshvchawla** [comment]
renamed branch `bubble-leftAnchor-cyan` to `bubble-texts`

**Pull request merged**
