### PR TITLE
Both skylines SVG are responsive

### PR DESCRIPTION
**Pull request by gh0stl0nely**

### CODE REVIEW

**Comment by gh0stl0nely** [comment]
@BBoutet1 You can just add one line of css to make the SVG responsive while maintaining the current structure. This PR is just to show that SVG responsiveness can be done fairly quickly and simultaneously solve the white space problem. Don't merge it since it's not up to date with master branch yet. 

I commented out the unresponsive components because those can be done by other members seperately. No need to overcomplicate things.

**Comment by BBoutet1** [comment]
One single file for the skyline please. Images are heavy.

**Comment by BBoutet1** [comment]
> @BBoutet1 You can just add one line of css to make the SVG responsive while maintaining the current structure. This PR is just to show that SVG responsiveness can be done fairly quickly and simultaneously solve the white space problem. Don't merge it since it's not up to date with master branch yet.
> 
> I commented out the unresponsive components because those can be done by other members separately. No need to overcomplicate things.

@gh0stl0nely images are responsive right. But for the components you commented out, it gives them hard time to put them on the top of the image. That's is why they use "position: absolute" to be able to put  their component on the top. The problem with "position: absolute" is that the element containing this property does not follow the normal html flow  leading to a more complicated gymnastic to make the component responsive inside the Mainlayout. Using a negative margin instead of absolute positioning could be a solution  but till now everyone is using position absolute and z-index to put text on the top of background images. Secondly skyline is the biggest image, it plays on performance duplicating this image and using it in img tag.

**Comment by gh0stl0nely** [comment]
Closing this

**Pull request closed without merging**
