### PR TITLE
The links now become purple on hover

### PR DESCRIPTION
**Pull request by airshiprook**
https://trello.com/c/xTyVjPmf/226-05hovering-navbar-should-show-active-links01

### CODE REVIEW

**Comment by airshiprook** [comment]
Oops, I did git add . which I shouldn't have done coz now my 1 line change is mixed in with all these other alien changes.
Heres the file I actually made the change in: NavTabs.js from line 207.
I added this 
"&:hover": {
        color: "#873FE2",
      },
Should not break anything.

**Comment by dghazi12** [comment]
Looks good @airshiprook ! I didn't notice any break in the code on my end but I was wondering if the purple hover should also be applied to the footer?

**Review by dghazi12 — DISMISSED** [review]

**Comment by hanlinc27** [comment]
hey @airshiprook  I believe this change should also show the bottom line turn purple on hover and not just the text if I'm not mistaken?
image

**Review by hanlinc27 — CHANGES_REQUESTED** [review]
could you please do a `git revert` to the last hash and then push a clean commit of your changes?

**Comment by dghazi12** [comment]
> hey @airshiprook I believe this change should also show the bottom line turn purple on hover and not just the text if I'm not mistaken?
> image

@hanlinc27 I believe it's good the way he has it because the figma shows this : 

Screen Shot 2020-10-21 at 5 11 49 PM

@dghazi12  exact and it makes sense keeping active and hover styles different @hanlinc27

**Comment by airshiprook** [comment]
Good idea on the git revert. Ill also add the hover on the footer links David, thanks for pointing that out.

**Comment by airshiprook** [comment]
Im still seeing changes that are not mine but this time I only added the files I changed (footer.js and navtabs.js). I guess this is as good as I can do it. I did a soft reset (git reset --soft HEAD~1) instead of the git revert to the previous hash. Only coz I just found out how to find the previous hash ha. Wont make a diff though I think...

**Review by BBoutet1 — APPROVED** [review]
It is ok for me.

**Review by hanlinc27 — APPROVED** [review]

**Pull request merged**
