### PR TITLE
Rishfilet/vital role section

### PR DESCRIPTION
**Pull request by rishFilet**
This is just an initial refactor for reusable components, to create similar sections for bottom line and vital role (on the partners page). I plan to further break it down for reusability in another PR (right now its a bit messy but a start). This also cleaned up a bunch of warnings, cleaned up console.log and style in burger menu. Changed the home in index.js for about us

### CODE REVIEW

**Comment by gh0stl0nely** [comment]
@rishFilet 

Some overall thoughts of mine:
- I like how you seperate the userStyle into another file. That definitely helps minimize conflicts down the line.

- Great initiative on the refactoring! From my point of view, a component can be reused if there is not much changes needed to be performed (or very very small changes) on that **shared** component - (Like Saint reuses the HeroText.js component and very little changes need to be made to hide the heart icon). 

- I understand your intention to reuse the GridContainerFile for both pages. However, I am not too much of a fan for doing this since there are some factors that are not shared between the two sections. For instance, there are 3 paragraphs in Partner page (we should fix it too) whereas there is only one paragraph in another. Maybe it can be fixed by doing some css styling to hide stuff but it will be messy as more pages share this component. In addition, the tablet version for Partner page is like this.

image

which is quite different from the mobile version of the donation page (if we plan on reusing the component). 

image

One may have to add additional child components/HTML tags into the GridContainerFile and will make the file quite messy. 

- In my opinion, we can create a copied version of the section that has been done (TheBottomLine.js) and make appropriate modification to suit the needs of other section from other pages. Three benefits: 1) Multiple teammates can work on seperate files without having to change the same refactored files and to avoid conflicts and 2) Changes to that specific sections only occur within that component file, and not to any shared, generic component like GridContainerFile.js and 3) Allows for customization for each section.

Would love to hear your thought.

**Comment by harshvchawla** [comment]
Disclaimer: Putting following comment without actually going through diff of the files bcos too much code change  for me to review lol (@rishFilet good job :O!!)

I concur what @gh0stl0nely  said about leveraging copying/modifying (WET) in certain cases over "argumented reusing" (DRY)
I remember having this discussion with @dghazi12 in some of the first code pieces, how we chose to "hardcode" pieces of configuration within code and deciding to copy/paste as per need

There is no right/wrong approach anyway, and its always good to balance between WET and DRY code principles in my opinion

When all this effort has already been put in this PR toward refactoring (and I am a huge fan of refactoring lol), we can choose to merge I guess ?(will try to actually review the file diffs too :p)

**Comment by rishFilet** [comment]
> @rishFilet
> 
> Some overall thoughts of mine:
> 
>     * I like how you seperate the userStyle into another file. That definitely helps minimize conflicts down the line.
> 
>     * Great initiative on the refactoring! From my point of view, a component can be reused if there is not much changes needed to be performed (or very very small changes) on that **shared** component - (Like Saint reuses the HeroText.js component and very little changes need to be made to hide the heart icon).
> 
>     * I understand your intention to reuse the GridContainerFile for both pages. However, I am not too much of a fan for doing this since there are some factors that are not shared between the two sections. For instance, there are 3 paragraphs in Partner page (we should fix it too) whereas there is only one paragraph in another. Maybe it can be fixed by doing some css styling to hide stuff but it will be messy as more pages share this component. In addition, the tablet version for Partner page is like this.
> 
> 
> image
> 
> which is quite different from the mobile version of the donation page (if we plan on reusing the component).
> 
> image
> 
> One may have to add additional child components/HTML tags into the GridContainerFile and will make the file quite messy.
> 
>     * In my opinion, we can create a copied version of the section that has been done (TheBottomLine.js) and make appropriate modification to suit the needs of other section from other pages. Three benefits: 1) Multiple teammates can work on seperate files without having to change the same refactored files and to avoid conflicts and 2) Changes to that specific sections only occur within that component file, and not to any shared, generic component like GridContainerFile.js and 3) Allows for customization for each section.
> 
> 
> Would love to hear your thought.

I do agree with both @gh0stl0nely and @harshvchawla but this is not the final version lol. As i mentioned and placed a ticket up on trello, i am going to further refactor this into smaller components. This is the ultimate goal i believe, which is to create a bunch of reusable components that we can plug and place anywhere. So while this is technically one reusable component. I am working backwards and the next step is to refactor the grid container into smaller components that can be edited based on the need for it. 

I appreciate the detailed response and review on this.  I'd say when that refactor is complete, then if it still does not work well (i doubt it will as it will be modular pieces), i can revert the commit back to it being two sections.

**Comment by gh0stl0nely** [comment]
> > @rishFilet
> > Some overall thoughts of mine:
> > ```
> > * I like how you seperate the userStyle into another file. That definitely helps minimize conflicts down the line.
> > 
> > * Great initiative on the refactoring! From my point of view, a component can be reused if there is not much changes needed to be performed (or very very small changes) on that **shared** component - (Like Saint reuses the HeroText.js component and very little changes need to be made to hide the heart icon).
> > 
> > * I understand your intention to reuse the GridContainerFile for both pages. However, I am not too much of a fan for doing this since there are some factors that are not shared between the two sections. For instance, there are 3 paragraphs in Partner page (we should fix it too) whereas there is only one paragraph in another. Maybe it can be fixed by doing some css styling to hide stuff but it will be messy as more pages share this component. In addition, the tablet version for Partner page is like this.
> > ```
> > 
> > 
> > image
> > which is quite different from the mobile version of the donation page (if we plan on reusing the component).
> > image
> > One may have to add additional child components/HTML tags into the GridContainerFile and will make the file quite messy.
> > ```
> > * In my opinion, we can create a copied version of the section that has been done (TheBottomLine.js) and make appropriate modification to suit the needs of other section from other pages. Three benefits: 1) Multiple teammates can work on seperate files without having to change the same refactored files and to avoid conflicts and 2) Changes to that specific sections only occur within that component file, and not to any shared, generic component like GridContainerFile.js and 3) Allows for customization for each section.
> > ```
> > 
> > 
> > Would love to hear your thought.
> 
> I do agree with both @gh0stl0nely and @harshvchawla but this is not the final version lol. As i mentioned and placed a ticket up on trello, i am going to further refactor this into smaller components. This is the ultimate goal i believe, which is to create a bunch of reusable components that we can plug and place anywhere. So while this is technically one reusable component. I am working backwards and the next step is to refactor the grid container into smaller components that can be edited based on the need for it.
> 
> I appreciate the detailed response and review on this. I'd say when that refactor is complete, then if it still does not work well (i doubt it will as it will be modular pieces), i can revert the commit back to it being two sections.

@rishFilet  Sure, we can look forward to the refactor version. Is it ok if we can keep the original files in place for the 2 sections for now, while you are working on refactoring the GridContainer file on a seperate branch? I just want to make sure that others who are working on fixing padding or styling on those sections can work on them without creating additional conflicts while waiting for your refactored version. Other parts like getting rid of console log, fixing burger style etc.. are good to merge.

**Comment by rishFilet** [comment]
> > > @rishFilet
> > > Some overall thoughts of mine:
> > > ```
> > > * I like how you seperate the userStyle into another file. That definitely helps minimize conflicts down the line.
> > > 
> > > * Great initiative on the refactoring! From my point of view, a component can be reused if there is not much changes needed to be performed (or very very small changes) on that **shared** component - (Like Saint reuses the HeroText.js component and very little changes need to be made to hide the heart icon).
> > > 
> > > * I understand your intention to reuse the GridContainerFile for both pages. However, I am not too much of a fan for doing this since there are some factors that are not shared between the two sections. For instance, there are 3 paragraphs in Partner page (we should fix it too) whereas there is only one paragraph in another. Maybe it can be fixed by doing some css styling to hide stuff but it will be messy as more pages share this component. In addition, the tablet version for Partner page is like this.
> > > ```
> > > 
> > > 
> > > image
> > > which is quite different from the mobile version of the donation page (if we plan on reusing the component).
> > > image
> > > One may have to add additional child components/HTML tags into the GridContainerFile and will make the file quite messy.
> > > ```
> > > * In my opinion, we can create a copied version of the section that has been done (TheBottomLine.js) and make appropriate modification to suit the needs of other section from other pages. Three benefits: 1) Multiple teammates can work on seperate files without having to change the same refactored files and to avoid conflicts and 2) Changes to that specific sections only occur within that component file, and not to any shared, generic component like GridContainerFile.js and 3) Allows for customization for each section.
> > > ```
> > > 
> > > 
> > > Would love to hear your thought.
> > 
> > 
> > I do agree with both @gh0stl0nely and @harshvchawla but this is not the final version lol. As i mentioned and placed a ticket up on trello, i am going to further refactor this into smaller components. This is the ultimate goal i believe, which is to create a bunch of reusable components that we can plug and place anywhere. So while this is technically one reusable component. I am working backwards and the next step is to refactor the grid container into smaller components that can be edited based on the need for it.
> > I appreciate the detailed response and review on this. I'd say when that refactor is complete, then if it still does not work well (i doubt it will as it will be modular pieces), i can revert the commit back to it being two sections.
> 
> @rishFilet Sure, we can look forward to the refactor version. Is it ok if we can keep the original files in place for the 2 sections for now, while you are working on refactoring the GridContainer file on a seperate branch? I just want to make sure that others who are working on fixing padding or styling on those sections can work on them without creating additional conflicts while waiting for your refactored version. Other parts like getting rid of console log, fixing burger style etc.. are good to merge.

Yea sounds good. Ill revert that part and leave the others and commit it.

**Comment by rishFilet** [comment]
@hanlinc27 @gh0stl0nely can you approve this with the added changes from hanlin so we can start using the reusable components

**Comment by gh0stl0nely** [comment]
@rishFilet Sure. I assume we are not following Figma design on this section. Or that is to be done later? 

image

**Review by gh0stl0nely — DISMISSED** [review]

**Comment by rishFilet** [comment]
> @rishFilet Sure. I assume we are not following Figma design on this section. Or that is to be done later?
> 
> image

Yup you are right. I added a card here for Blendi/cynthia to update the figma to match our code rather than the design as they agree it looks fine and wouldn't be worth a whole lot to make the change to look exactly like this. https://trello.com/c/XOREgyOo

**Comment by rishFilet** [comment]
@demiwu96 @dghazi12 @BBoutet1 @airshiprook @harshvchawla

**Comment by gh0stl0nely** [comment]
> @demiwu96 @dghazi12 @BBoutet1 @airshiprook @harshvchawla

sounds good that makes life 101% easier.

**Review by BBoutet1 — DISMISSED** [review]
@gh0stl0nely approved

**Pull request merged**
