### PR TITLE
Rishfilet/refactor hero sections

### PR DESCRIPTION
**Pull request by rishFilet**
A lot was done in this PR:
1. Deleted the shared folder and moved them into components in their own folders
2. Refactored the Hero sections to be more generic and only changing their specific attributes using the inline style for that component
3. Refactored the Bottom line and vital role section as a result of (2)
4. Fixed the skyline header to fit closer to what is outlined in figma

Sorry for the long PR, what started as a simple refactor ended up taking a lot longer

### CODE REVIEW

**Comment by gh0stl0nely** [comment]
@rishFilet  Few things I noticed 

1) The Skyline is out of place 
image

2) Background SVG and part of these SVGS are gone
image

3) The two cheetos are out of place.

image

**Comment by BBoutet1** [comment]
@rishFilet @gh0stl0nely Compare to what is in Figma, you have "zoomed" the skyline giving it a bigger height (image below). As a result this section is higher and goes outside the viewport with the skyline out of place. The easiest solution to manage with Figma ratio is to put the image in background or make some gymnastic with css to responsively hide a section and show the other part of the picture. In both cases, you can use the full skyline image I already downloaded without cutting it like it is done here.

I suggest to remove first this **ZOOM** on the skyline. This is what I started to do the last time.

image

**Comment by BBoutet1** [comment]
@rishFilet 

Below is the full skyline image. I don't find any more the one I downloaded in the repo.  But you can still download it. Use it entirely and use the same file on the footer(timeline) and header(hero) by selecting the side you want to show (right for the hero section and left for the timeline section) and the one you want to hide.  You can see on Figma that the shown part is not the same from small to big size screen to play effectively with the image height without squeezing the image to cover the viewport width.

image


To make the shown and hidden sections variable, it is easier to achieve this in background-image solution.

**Comment by rishFilet** [comment]
> @rishFilet Few things I noticed
> 
>     1. The Skyline is out of place
>        image
> 
>     2. Background SVG and part of these SVGS are gone
>        image
> 
>     3. The two cheetos are out of place.
> 
> 
> image

Fixed, however the images seem to be an issue with pulling them from figma. The middle image is different to the other two and the background blobs are coming in as white so they melt to the already white card.

**Comment by rishFilet** [comment]
> @rishFilet
> 
> Below is the full skyline image. I don't find any more the one I downloaded in the repo. But you can still download it. Use it entirely and use the same file on the footer(timeline) and header(hero) by selecting the side you want to show (right for the hero section and left for the timeline section) and the one you want to hide. You can see on Figma that the shown part is not the same from small to big size screen to play effectively with the image height without squeezing the image to cover the viewport width.
> 
> image
> 
> To make the shown and hidden sections variable, it is easier to achieve this in background-image solution.

Let's handle this in another PR. Possible have to check with design on the size and original image

**Pull request merged**
