### PR TITLE
Refining the "src" structure: shorter component integration.

### PR DESCRIPTION
**Pull request by BBoutet1**
A - "components/Home" renamed to "components/AboutUs".

B -This new structure reduces the components integration steps (files manipulation).
- Component integration process with the previous structure : 
    1-build the component (e.g: "components/AboutUs/HowAreWeDifferentSection.js")  2- update the export from "components/AboutUs/index.js" 3- update the import in "pages/index.js"
- Component integration process with the new structure : 
    1-build the component (e.g: "components/AboutUs/HowAreWeDifferentSection.js")  2- update the import from "components/AboutUs/index.js". 

"pages/index.js" like the others "pages" files can be considered final from now.

### CODE REVIEW

**Comment by gh0stl0nely** [comment]
Code will be frozen soon so I will leave it for now. But I think the structure looks fine.

**Comment by BBoutet1** [comment]
@gh0stl0nely a latest pull request  from @hanlinc27 has been approved resulting in creating conflicts on this one. Hanlin made the pull request 1 hour later.

**Comment by gh0stl0nely** [comment]
> @gh0stl0nely a latest pull request from @hanlinc27 has been approved resulting in creating conflicts on this one. Hanlin made the pull request 1 hour later.

Yes I figured. We will bring it up on Monday @BBoutet1

**Comment by gh0stl0nely** [comment]
@BBoutet1  Can you delete the react.js file? I don't think it is necessary.

image

**Comment by BBoutet1** [comment]
I did not touch the navbar. Just moved the MainLayout wrapper you made from
AbousUs/index.js to pages/index.js. Maybe this is the reason. Ok for
changes later on.

**Comment by BBoutet1** [comment]
@gh0stl0nely someone else will delete the react.js file. I have already deleted some unused files and imports. There is nothing new with the navbar. Just the background color or the transparency need to be fixed.

**Comment by gh0stl0nely** [comment]
> @gh0stl0nely someone else will delete the react.js file. I have already deleted some unused files and imports. There is nothing new with the navbar. Just the background color or the transparency need to be fixed.

Who will delete the file - better to do it so everyone can just pull the latest structural change. 

I manually tested the code and see that the navbar is out of place. If you don't mind I will pull all these changes to my branch and create a pull request that is more complete. @BBoutet1

**Comment by BBoutet1** [comment]
I don't know why thid React.js has been created. Anyone can clean the code. I am not sure we should keep all the team in standby for small tweaks. The improvement is continuous once we idenfy where it should be done.

**Comment by BBoutet1** [comment]
@gh0stl0nely feel free to pull in your branch and improve.

**Review by hanlinc27 — APPROVED** [review]

**Comment by gh0stl0nely** [comment]
> @gh0stl0nely feel free to pull in your branch and improve.

I just did and created a new PR. Can you review?

**Pull request closed without merging**
