### PR TITLE
https://trello.com/c/ROILIYDI/166-2deliver-partners-thank-for-partnering-part05

### PR DESCRIPTION
**Pull request by airshiprook**
1. This branch should really be named DeliveryPartners+FuncNameChange
2. Changed Function name from Home to AboutUs in component file AboutUs/index.js
3. Added the Thank You for.. HeroText component for Partners Page
4. Added SVGSkyline
5. Applied a Hacky solution to get rid of the Rainbow Heart Icon as its currently embedded in the HeroText component and I could not come up with anything better ATM.

### CODE REVIEW

**Comment by gh0stl0nely** [comment]
@airshiprook  This is good. For the heart icon, i think one way to do it is to check the path of the current url, although your solution works as well. 

If the path ends with "/partners", you can apply a display none inline-styles on that heart icon specifically, else just use the original styling on the same file. You probably don't need to create another css file for that one class.

**Comment by gh0stl0nely** [comment]
@airshiprook We can approve this change after you merge with master.

**Comment by BBoutet1** [comment]
@airshiprook we would like to see your changes within the latest master version to make sure that everything is ok with the entire page layout. Please merge the latest master, no upcoming conflict. You are behind.

**Comment by airshiprook** [comment]
After I merge with master?  You mean Im behind in this pr?
Also I had another thought for the rainbow img. 
A conditional statement that applies display none by defualt unless its on the AboutUs path. Where would I write this logic though? Wanna have a go at this? 
Another way could be to have img display none in a global css file and override that in HeroText.module.css.

**Comment by airshiprook** [comment]
Ahh, I just hit the update branch button. The tests are running now.

**Comment by airshiprook** [comment]
All checks PASSED!

**Comment by gh0stl0nely** [comment]
> After I merge with master? You mean Im behind in this pr?
> Also I had another thought for the rainbow img.
> A conditional statement that applies display none by defualt unless its on the AboutUs path. Where would I write this logic though? Wanna have a go at this?
> Another way could be to have img display none in a global css file and override that in HeroText.module.css.

I mean this is good - your approach makes sense for sure. The branch should be up-to-date with master now. I am just throwing ideas out to get some creative juice going. If you want to tackle it using my approach, you can try in your own time but it will involve playing around with the `window` object, but this is good to be merged imo.

**Review by gh0stl0nely — APPROVED** [review]

**Comment by airshiprook** [comment]
Thanks. Ill make a note to find a solution as otherwise we would need to replicate a css file just for this hack for every page lol.
I agree with you that its Good enough for now though!

**Comment by gh0stl0nely** [comment]
@airshiprook Yup, and feel free to merge once we got 2 approvals!

**Review by BBoutet1 — APPROVED** [review]

**Review by dghazi12 — APPROVED** [review]

**Pull request merged**
