### PR TITLE
Changed padding for About Us: our roots

### PR DESCRIPTION
**Pull request by hanlinc27**
- Changed top and bottom padding to be 96px (as per Figma file)
- Changed where the text breaks (as per Figma file)
- Trello card [here](https://trello.com/c/MxA9jdqi)

### CODE REVIEW

**Comment by gh0stl0nely** [comment]
@hanlinc27 At some point on the mobile version, the text seems odd.

image

**Comment by hanlinc27** [comment]
@gh0stl0nely do you suggest taking out the breaks entirely then?

**Comment by gh0stl0nely** [comment]
> @gh0stl0nely do you suggest taking out the breaks entirely then?

@hanlinc27 If doing so fixes the problem, that would be fine.

**Comment by hanlinc27** [comment]
@gh0stl0nely I changed the padding left/right for smaller screens to be the same as Figma (27px) that seems to fix it.

**Comment by gh0stl0nely** [comment]
@hanlinc27 Looks good, to be honest I wouldn't be too obsessed with responsiveness because as of now if I resize the screen, at some point, there will be problem like these that occur that is not exactly the same as Figma - 2 lines instead of 3 lines  (below). If we are following Figma exactly, let's maybe create another breakpoint for small screen and change the left and right padding appropriately, but if not, then now should be fine. What do you think? 

image

image

**Comment by hanlinc27** [comment]
@gh0stl0nely  Ok then let's just keep it as is for now and if we want to do another breakpoint that can be a new ticket. This ticket was supposed to be for top/bottom padding anyways - if you could approve this PR that'd be great 👍

**Comment by gh0stl0nely** [comment]
> @gh0stl0nely Ok then let's just keep it as is for now and if we want to do another breakpoint that can be a new ticket. This ticket was supposed to be for top/bottom padding anyways - if you could approve this PR that'd be great 👍

@hanlinc27 Hmm I thought it will be about changing the entire paddings, including right and left. I think we can keep this PR up for now, and when you have time (no rush of course), can you also fix the left and right padding so that it follows Figma's design since I think that is also part of the problem as of now? 

@demiwu96 What do you think?

**Comment by hanlinc27** [comment]
@gh0stl0nely  what part about the left and right padding for "our roots"? I don't see any discrepancies on my side right now?

**Comment by gh0stl0nely** [comment]
> @gh0stl0nely what part about the left and right padding for "our roots"? I don't see any discrepancies on my side right now?

@hanlinc27 As above, the left and right padding on Figma file is like this.
image

Currently this is how it is on our site (on med-small screen) - left and right paddings are not big enough on certain screen sizes. I believe this discrepancy can be found on desktop/ big screen over 1700px. 

image

It's not quite the same because there are 3 lines instead of 2, but as I also said, if you think it is not necessary to make it look exactly the same as Figma, then right now it is ok.

**Comment by gh0stl0nely** [comment]
@hanlinc27 honestly i think this is good its just these few nuances that may need to be taken care of sooner or later.

**Pull request merged**
