### PR TITLE
Dghazi/why tech responsiveness

### PR DESCRIPTION
**Pull request by dghazi12**
Few comments: 

- Simply just have the 4 components in the WhyTech/ValuesDriven section displayed.
- The SVG image next to the Why Tech text is missing the lightbulb - will address this issue with Blendi.
- The alignment/responsiveness still needs to be fixed on this section - work in progress.
- Image sizes should be correct, positioning will be off until section is responsive.

### CODE REVIEW

**Comment by gh0stl0nely** [comment]
@dghazi12 
Some bugs I saw after I tested your branch

1) These cards have weird styling (did you merge with master?)
image

2) This image in this section is gone. 
image

**Comment by dghazi12** [comment]
> @dghazi12
> Some bugs I saw after I tested your branch
> 
> 1. These cards have weird styling (did you merge with master?)
>    image
> 2. This image in this section is gone.
>    image

@gh0stl0nely I did a merge with master. Not sure why this happened, I will look into it and fix it.

**Comment by gh0stl0nely** [comment]
> > @dghazi12
> > Some bugs I saw after I tested your branch
> > 
> > 1. These cards have weird styling (did you merge with master?)
> >    image
> > 2. This image in this section is gone.
> >    image
> 
> @gh0stl0nely I did a merge with master. Not sure why this happened, I will look into it and fix it.

It seems that this branch is not up to date yet. 

image

**Comment by dghazi12** [comment]
> > > @dghazi12
> > > Some bugs I saw after I tested your branch
> > > 
> > > 1. These cards have weird styling (did you merge with master?)
> > >    image
> > > 2. This image in this section is gone.
> > >    image
> > 
> > 
> > @gh0stl0nely I did a merge with master. Not sure why this happened, I will look into it and fix it.
> 
> It seems that this branch is not up to date yet.
> 
> image

@gh0stl0nely I realized my mistake with the cards. That should be corrected now. Still looking into why that image has disappeared. Not exactly sure where I went wrong just yet.

**Comment by dghazi12** [comment]
> > > @dghazi12
> > > Some bugs I saw after I tested your branch
> > > 
> > > 1. These cards have weird styling (did you merge with master?)
> > >    image
> > > 2. This image in this section is gone.
> > >    image
> > 
> > 
> > @gh0stl0nely I did a merge with master. Not sure why this happened, I will look into it and fix it.
> 
> It seems that this branch is not up to date yet.
> 
> image

@gh0stl0nely Image in bottom line section now appears. Should be all fixed.

**Comment by BBoutet1** [comment]
@gh0stl0nely @harshvchawla @rishFilet  note that I am waiting this PR to be approved as I need to modify "AboutIUs/index.js" while fixing HeroText component. Better if I can integrate @dghazi12 modifications from the master first to avoid conflicts in his PR or mine depending on which one will be integrated first.

**Comment by gh0stl0nely** [comment]
> > > > @dghazi12
> > > > Some bugs I saw after I tested your branch
> > > > 
> > > > 1. These cards have weird styling (did you merge with master?)
> > > >    image
> > > > 2. This image in this section is gone.
> > > >    image
> > > 
> > > 
> > > @gh0stl0nely I did a merge with master. Not sure why this happened, I will look into it and fix it.
> > 
> > 
> > It seems that this branch is not up to date yet.
> > image
> 
> @gh0stl0nely Image in bottom line section now appears. Should be all fixed.

@dghazi12 This is good progress. I will approve but since we are on a code-freeze so anyone who will merge with master, do so on Monday.

**Review by gh0stl0nely — APPROVED** [review]

**Review by BBoutet1 — APPROVED** [review]

**Pull request merged**
