### PR TITLE
Organization section on delivery partner page

### PR DESCRIPTION
**Pull request by demiwu96**

### CODE REVIEW

**Comment by gh0stl0nely** [comment]
@demiwu96 Reduce the space between the cards. 
 
image

**Comment by gh0stl0nely** [comment]
Also sometimes on smaller screen the words are distorted. Maybe adjust the font size as it resizes. 

image

**Comment by demiwu96** [comment]
> Also sometimes on smaller screen the words are distorted. Maybe adjust the font size as it resizes.
> 
> image

fixed

**Comment by demiwu96** [comment]
> @demiwu96 Reduce the space between the cards.
> 
> image



> @demiwu96 Reduce the space between the cards.
> 
> image

fixed

**Comment by gh0stl0nely** [comment]
@demiwu96  @hanlinc27 I think this is good although sometimes the cards' size become slightly "unbalance" when being resized to smaller screen. Do you guys think this is good enough for now? (I just tested out manually after Demi made these changes above)

**Review by hanlinc27 — CHANGES_REQUESTED** [review]
image
 I'm still seeing the unbalance between the cards?

**Pull request closed without merging**
