### PR TITLE
Rishfilet/preloading images fonts

### PR DESCRIPTION
**Pull request by rishFilet**
DON"T PANIC! This PR will cause the loading to be almost 6 seconds in firefox, some reason in chrome it works fine. However all the components load on screen together which looks nice when actually loaded. The problem after investigating with profiler is the timeline section which takes the most time to load , around 4-5 seconds. This could be due to the images and having to preload them as i changed them to components using the gatsby plugin. This was also suggested as an optimizer for performance to load the SVGs as components. So the next step is to figure out why the timeline sections takes so long to load. Perhaps we are rendering the component in the wrong order? :man_shrugging: 

Fixed the loading of the skyline svg and the fonts not loading as previously stated in my last PR.

## Firefox:
image
image

## Chrome
image

### CODE REVIEW

**Review by BBoutet1 — COMMENTED** [review]
@rishFilet the deploy failed. Please, can you fix that first?

**Comment by rishFilet** [comment]
> @rishFilet the deploy failed. Please, can you fix that first?

Trying again. Seems to be an issue with the web font loader plugin i added

**Review by BBoutet1 — APPROVED** [review]

**Review by gh0stl0nely — APPROVED** [review]
Definitely looks very neat. Great job @rishFilet ! We can think about how to optimize cross browser afterwards, but the site on Chrome looks good.

**Comment by gh0stl0nely** [comment]
@rishFilet I think this is good although if possible it would be better to add SVG (i.e: PeopleSVG) at the end of the React component that you re-created for the SVG just for us as developers know that it is a SVG component.

**Comment by hanlinc27** [comment]
@rishFilet  It takes me 10+ seconds to load it on Chrome. I wonder if it's worth having this simultaneous load and maybe try lazy-loading the images instead?

**Comment by gh0stl0nely** [comment]
For reference: Lazy-load can be achieved with gatsby-image that auto lazy-loads.

**Comment by gh0stl0nely** [comment]
Can use gatsby-image for automatic lazy-loading? I actually prefer React Lazy but it does not support Server Side Rendering sadly.  

https://www.gatsbyjs.com/plugins/gatsby-image/

**Comment by rishFilet** [comment]
> @rishFilet I think this is good although if possible it would be better to add SVG (i.e: PeopleSVG) at the end of the React component that you re-created for the SVG just for us as developers know that it is a SVG component.

Ill make this change

**Comment by rishFilet** [comment]
> @rishFilet It takes me 10+ seconds to load it on Chrome. I wonder if it's worth having this simultaneous load and maybe try lazy-loading the images instead?

hmm thsi is strange as chrome i was seeing it load faster. Do you mean it takes 10 seconds for all the elements to load or using the inspector tool you see it finishes at 10 seconds? I will look into the lazy loading as well. I was avoiding using it as it seemed to cause people pain online, but ill try it out, might be the solution for it

**Pull request merged**
